package com.example.deepsudoku

import android.content.res.AssetManager
import android.graphics.Bitmap
import android.graphics.Typeface
import android.net.Uri
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.fragment.app.Fragment
import com.example.deepsudoku.databinding.FragmentSolutionViewBinding
import java.lang.reflect.Type

class SolutionViewFragment : Fragment() {
    private var _viewBinding: FragmentSolutionViewBinding? = null
    private val viewBinding: FragmentSolutionViewBinding get() = _viewBinding!!

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _viewBinding = FragmentSolutionViewBinding.inflate(inflater, container, false)
        var sudoku = arguments?.getIntegerArrayList("Sudoku")!!
        var solvedSudoku = arguments?.getIntegerArrayList("SolvedSudoku")!!

        viewBinding.cell00.text = solvedSudoku.get(0).toString()
        if(sudoku.get(0) > 0)
            viewBinding.cell00.setTypeface(null, Typeface.BOLD)
        viewBinding.cell01.text = solvedSudoku.get(1).toString()
        if(sudoku.get(1) > 0)
            viewBinding.cell01.setTypeface(null, Typeface.BOLD)
        viewBinding.cell02.text = solvedSudoku.get(2).toString()
        if(sudoku.get(2) > 0)
            viewBinding.cell02.setTypeface(null, Typeface.BOLD)
        viewBinding.cell03.text = solvedSudoku.get(3).toString()
        if(sudoku.get(3) > 0)
            viewBinding.cell03.setTypeface(null, Typeface.BOLD)
        viewBinding.cell04.text = solvedSudoku.get(4).toString()
        if(sudoku.get(0) > 0)
            viewBinding.cell04.setTypeface(null, Typeface.BOLD)
        viewBinding.cell05.text = solvedSudoku.get(5).toString()
        if(sudoku.get(5) > 0)
            viewBinding.cell05.setTypeface(null, Typeface.BOLD)
        viewBinding.cell06.text = solvedSudoku.get(6).toString()
        if(sudoku.get(6) > 0)
            viewBinding.cell06.setTypeface(null, Typeface.BOLD)
        viewBinding.cell07.text = solvedSudoku.get(7).toString()
        if(sudoku.get(7) > 0)
            viewBinding.cell07.setTypeface(null, Typeface.BOLD)
        viewBinding.cell08.text = solvedSudoku.get(8).toString()
        if(sudoku.get(8) > 0)
            viewBinding.cell08.setTypeface(null, Typeface.BOLD)

        viewBinding.cell10.text = solvedSudoku.get(9).toString()
        if(sudoku.get(9) > 0)
            viewBinding.cell10.setTypeface(null, Typeface.BOLD)
        viewBinding.cell11.text = solvedSudoku.get(10).toString()
        if(sudoku.get(10) > 0)
            viewBinding.cell11.setTypeface(null, Typeface.BOLD)
        viewBinding.cell12.text = solvedSudoku.get(11).toString()
        if(sudoku.get(11) > 0)
            viewBinding.cell12.setTypeface(null, Typeface.BOLD)
        viewBinding.cell13.text = solvedSudoku.get(12).toString()
        if(sudoku.get(12) > 0)
            viewBinding.cell13.setTypeface(null, Typeface.BOLD)
        viewBinding.cell14.text = solvedSudoku.get(13).toString()
        if(sudoku.get(13) > 0)
            viewBinding.cell14.setTypeface(null, Typeface.BOLD)
        viewBinding.cell15.text = solvedSudoku.get(14).toString()
        if(sudoku.get(14) > 0)
            viewBinding.cell15.setTypeface(null, Typeface.BOLD)
        viewBinding.cell16.text = solvedSudoku.get(15).toString()
        if(sudoku.get(15) > 0)
            viewBinding.cell16.setTypeface(null, Typeface.BOLD)
        viewBinding.cell17.text = solvedSudoku.get(16).toString()
        if(sudoku.get(16) > 0)
            viewBinding.cell17.setTypeface(null, Typeface.BOLD)
        viewBinding.cell18.text = solvedSudoku.get(17).toString()
        if(sudoku.get(17) > 0)
            viewBinding.cell18.setTypeface(null, Typeface.BOLD)

        viewBinding.cell20.text = solvedSudoku.get(18).toString()
        if(sudoku.get(18) > 0)
            viewBinding.cell20.setTypeface(null, Typeface.BOLD)
        viewBinding.cell21.text = solvedSudoku.get(19).toString()
        if(sudoku.get(19) > 0)
            viewBinding.cell21.setTypeface(null, Typeface.BOLD)
        viewBinding.cell22.text = solvedSudoku.get(20).toString()
        if(sudoku.get(20) > 0)
            viewBinding.cell22.setTypeface(null, Typeface.BOLD)
        viewBinding.cell23.text = solvedSudoku.get(21).toString()
        if(sudoku.get(21) > 0)
            viewBinding.cell23.setTypeface(null, Typeface.BOLD)
        viewBinding.cell24.text = solvedSudoku.get(22).toString()
        if(sudoku.get(22) > 0)
            viewBinding.cell24.setTypeface(null, Typeface.BOLD)
        viewBinding.cell25.text = solvedSudoku.get(23).toString()
        if(sudoku.get(23) > 0)
            viewBinding.cell25.setTypeface(null, Typeface.BOLD)
        viewBinding.cell26.text = solvedSudoku.get(24).toString()
        if(sudoku.get(24) > 0)
            viewBinding.cell26.setTypeface(null, Typeface.BOLD)
        viewBinding.cell27.text = solvedSudoku.get(25).toString()
        if(sudoku.get(25) > 0)
            viewBinding.cell27.setTypeface(null, Typeface.BOLD)
        viewBinding.cell28.text = solvedSudoku.get(26).toString()
        if(sudoku.get(26) > 0)
            viewBinding.cell28.setTypeface(null, Typeface.BOLD)


        viewBinding.cell30.text = solvedSudoku.get(27).toString()
        if(sudoku.get(27) > 0)
            viewBinding.cell30.setTypeface(null, Typeface.BOLD)
        viewBinding.cell31.text = solvedSudoku.get(28).toString()
        if(sudoku.get(28) > 0)
            viewBinding.cell31.setTypeface(null, Typeface.BOLD)
        viewBinding.cell32.text = solvedSudoku.get(29).toString()
        if(sudoku.get(29) > 0)
            viewBinding.cell32.setTypeface(null, Typeface.BOLD)
        viewBinding.cell33.text = solvedSudoku.get(30).toString()
        if(sudoku.get(30) > 0)
            viewBinding.cell08.setTypeface(null, Typeface.BOLD)
        viewBinding.cell34.text = solvedSudoku.get(31).toString()
        if(sudoku.get(31) > 0)
            viewBinding.cell34.setTypeface(null, Typeface.BOLD)
        viewBinding.cell35.text = solvedSudoku.get(32).toString()
        if(sudoku.get(32) > 0)
            viewBinding.cell35.setTypeface(null, Typeface.BOLD)
        viewBinding.cell36.text = solvedSudoku.get(33).toString()
        if(sudoku.get(33) > 0)
            viewBinding.cell36.setTypeface(null, Typeface.BOLD)
        viewBinding.cell37.text = solvedSudoku.get(34).toString()
        if(sudoku.get(34) > 0)
            viewBinding.cell37.setTypeface(null, Typeface.BOLD)
        viewBinding.cell38.text = solvedSudoku.get(35).toString()
        if(sudoku.get(35) > 0)
            viewBinding.cell38.setTypeface(null, Typeface.BOLD)

        viewBinding.cell40.text = solvedSudoku.get(36).toString()
        if(sudoku.get(36) > 0)
            viewBinding.cell40.setTypeface(null, Typeface.BOLD)
        viewBinding.cell41.text = solvedSudoku.get(37).toString()
        if(sudoku.get(37) > 0)
            viewBinding.cell41.setTypeface(null, Typeface.BOLD)
        viewBinding.cell42.text = solvedSudoku.get(38).toString()
        if(sudoku.get(38) > 0)
            viewBinding.cell42.setTypeface(null, Typeface.BOLD)
        viewBinding.cell43.text = solvedSudoku.get(39).toString()
        if(sudoku.get(39) > 0)
            viewBinding.cell43.setTypeface(null, Typeface.BOLD)
        viewBinding.cell44.text = solvedSudoku.get(40).toString()
        if(sudoku.get(40) > 0)
            viewBinding.cell44.setTypeface(null, Typeface.BOLD)
        viewBinding.cell45.text = solvedSudoku.get(41).toString()
        if(sudoku.get(41) > 0)
            viewBinding.cell45.setTypeface(null, Typeface.BOLD)
        viewBinding.cell46.text = solvedSudoku.get(42).toString()
        if(sudoku.get(42) > 0)
            viewBinding.cell46.setTypeface(null, Typeface.BOLD)
        viewBinding.cell47.text = solvedSudoku.get(43).toString()
        if(sudoku.get(43) > 0)
            viewBinding.cell47.setTypeface(null, Typeface.BOLD)
        viewBinding.cell48.text = solvedSudoku.get(44).toString()
        if(sudoku.get(44) > 0)
            viewBinding.cell48.setTypeface(null, Typeface.BOLD)

        viewBinding.cell50.text = solvedSudoku.get(45).toString()
        if(sudoku.get(45) > 0)
            viewBinding.cell50.setTypeface(null, Typeface.BOLD)
        viewBinding.cell51.text = solvedSudoku.get(46).toString()
        if(sudoku.get(46) > 0)
            viewBinding.cell51.setTypeface(null, Typeface.BOLD)
        viewBinding.cell52.text = solvedSudoku.get(47).toString()
        if(sudoku.get(47) > 0)
            viewBinding.cell52.setTypeface(null, Typeface.BOLD)
        viewBinding.cell53.text = solvedSudoku.get(48).toString()
        if(sudoku.get(48) > 0)
            viewBinding.cell53.setTypeface(null, Typeface.BOLD)
        viewBinding.cell54.text = solvedSudoku.get(49).toString()
        if(sudoku.get(49) > 0)
            viewBinding.cell54.setTypeface(null, Typeface.BOLD)
        viewBinding.cell55.text = solvedSudoku.get(50).toString()
        if(sudoku.get(50) > 0)
            viewBinding.cell55.setTypeface(null, Typeface.BOLD)
        viewBinding.cell56.text = solvedSudoku.get(51).toString()
        if(sudoku.get(51) > 0)
            viewBinding.cell56.setTypeface(null, Typeface.BOLD)
        viewBinding.cell57.text = solvedSudoku.get(52).toString()
        if(sudoku.get(52) > 0)
            viewBinding.cell57.setTypeface(null, Typeface.BOLD)
        viewBinding.cell58.text = solvedSudoku.get(53).toString()
        if(sudoku.get(53) > 0)
            viewBinding.cell58.setTypeface(null, Typeface.BOLD)



        viewBinding.cell60.text = solvedSudoku.get(54).toString()
        if(sudoku.get(54) > 0)
            viewBinding.cell60.setTypeface(null, Typeface.BOLD)
        viewBinding.cell61.text = solvedSudoku.get(55).toString()
        if(sudoku.get(55) > 0)
            viewBinding.cell61.setTypeface(null, Typeface.BOLD)
        viewBinding.cell62.text = solvedSudoku.get(56).toString()
        if(sudoku.get(56) > 0)
            viewBinding.cell62.setTypeface(null, Typeface.BOLD)
        viewBinding.cell63.text = solvedSudoku.get(57).toString()
        if(sudoku.get(57) > 0)
            viewBinding.cell63.setTypeface(null, Typeface.BOLD)
        viewBinding.cell64.text = solvedSudoku.get(58).toString()
        if(sudoku.get(58) > 0)
            viewBinding.cell64.setTypeface(null, Typeface.BOLD)
        viewBinding.cell65.text = solvedSudoku.get(59).toString()
        if(sudoku.get(59) > 0)
            viewBinding.cell65.setTypeface(null, Typeface.BOLD)
        viewBinding.cell66.text = solvedSudoku.get(60).toString()
        if(sudoku.get(60) > 0)
            viewBinding.cell66.setTypeface(null, Typeface.BOLD)
        viewBinding.cell67.text = solvedSudoku.get(61).toString()
        if(sudoku.get(61) > 0)
            viewBinding.cell67.setTypeface(null, Typeface.BOLD)
        viewBinding.cell68.text = solvedSudoku.get(62).toString()
        if(sudoku.get(62) > 0)
            viewBinding.cell68.setTypeface(null, Typeface.BOLD)

        viewBinding.cell70.text = solvedSudoku.get(63).toString()
        if(sudoku.get(63) > 0)
            viewBinding.cell70.setTypeface(null, Typeface.BOLD)
        viewBinding.cell71.text = solvedSudoku.get(64).toString()
        if(sudoku.get(64) > 0)
            viewBinding.cell71.setTypeface(null, Typeface.BOLD)
        viewBinding.cell72.text = solvedSudoku.get(65).toString()
        if(sudoku.get(65) > 0)
            viewBinding.cell72.setTypeface(null, Typeface.BOLD)
        viewBinding.cell73.text = solvedSudoku.get(66).toString()
        if(sudoku.get(66) > 0)
            viewBinding.cell73.setTypeface(null, Typeface.BOLD)
        viewBinding.cell74.text = solvedSudoku.get(67).toString()
        if(sudoku.get(67) > 0)
            viewBinding.cell74.setTypeface(null, Typeface.BOLD)
        viewBinding.cell75.text = solvedSudoku.get(68).toString()
        if(sudoku.get(68) > 0)
            viewBinding.cell75.setTypeface(null, Typeface.BOLD)
        viewBinding.cell76.text = solvedSudoku.get(69).toString()
        if(sudoku.get(69) > 0)
            viewBinding.cell76.setTypeface(null, Typeface.BOLD)
        viewBinding.cell77.text = solvedSudoku.get(70).toString()
        if(sudoku.get(70) > 0)
            viewBinding.cell77.setTypeface(null, Typeface.BOLD)
        viewBinding.cell78.text = solvedSudoku.get(71).toString()
        if(sudoku.get(71) > 0)
            viewBinding.cell78.setTypeface(null, Typeface.BOLD)

        viewBinding.cell80.text = solvedSudoku.get(72).toString()
        if(sudoku.get(72) > 0)
            viewBinding.cell80.setTypeface(null, Typeface.BOLD)
        viewBinding.cell81.text = solvedSudoku.get(73).toString()
        if(sudoku.get(73) > 0)
            viewBinding.cell81.setTypeface(null, Typeface.BOLD)
        viewBinding.cell82.text = solvedSudoku.get(74).toString()
        if(sudoku.get(74) > 0)
            viewBinding.cell82.setTypeface(null, Typeface.BOLD)
        viewBinding.cell83.text = solvedSudoku.get(75).toString()
        if(sudoku.get(75) > 0)
            viewBinding.cell83.setTypeface(null, Typeface.BOLD)
        viewBinding.cell84.text = solvedSudoku.get(76).toString()
        if(sudoku.get(76) > 0)
            viewBinding.cell84.setTypeface(null, Typeface.BOLD)
        viewBinding.cell85.text = solvedSudoku.get(77).toString()
        if(sudoku.get(77) > 0)
            viewBinding.cell85.setTypeface(null, Typeface.BOLD)
        viewBinding.cell86.text = solvedSudoku.get(78).toString()
        if(sudoku.get(78) > 0)
            viewBinding.cell86.setTypeface(null, Typeface.BOLD)
        viewBinding.cell87.text = solvedSudoku.get(79).toString()
        if(sudoku.get(79) > 0)
            viewBinding.cell87.setTypeface(null, Typeface.BOLD)
        viewBinding.cell88.text = solvedSudoku.get(80).toString()
        if(sudoku.get(80) > 0)
            viewBinding.cell88.setTypeface(null, Typeface.BOLD)


        return viewBinding.root
    }
}